Change CmsInfo themes to theme_name and theme_version
alma/alma-php-client pull request #146
Opened 2024-10-29 15:56 UTC by joyet-simon

### Reason for change

[Linear task](https://linear.app/almapay/issue/ECOM-XXX)
Schemas change in main's BDD

### Code changes

### How to test

_As a reviewer, you are encouraged to test the PR locally._

### Checklist for authors and reviewers

- [ ] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it
- [ ] The PR implements the changes asked in the referenced task / issue
- [ ] The automated tests are compliant with the [testing strategy](https://www.notion.so/almapay/Backend-testing-strategy-06c642cec1bf47b9b8feca3a91ea8d4a)
- [ ] The tests are relevant, and cover the corner/error cases, not only the happy path
- [ ] You understand the impact of this PR on existing code/features
- [ ] The changes include adequate logging and Datadog traces
- [ ] Documentation is updated (API, developer documentation, ADR, Notion...)

### Non applicable

2024-10-29 16:24 UTC, webaaz reviewed
Why don't we use constant?

2024-10-29 17:30 UTC, Benjamin-Freoua-Alma reviewed
There is a lint issue between tabs and space in this PR

2024-10-30 08:59 UTC, Benjamin-Freoua-Alma requested changes

2024-10-30 08:59 UTC, Benjamin-Freoua-Alma commented on src/Entities/MerchantData/CmsInfo.php
> +        $this->theme_version = isset($cmsInfoDataArray['theme_version']) ? $cmsInfoDataArray['theme_version'] : '';
these properties are in snake_case but other in camelCase :/

2024-10-30 09:04 UTC, Benjamin-Freoua-Alma approved these changes

2024-10-30 09:05 UTC, merged